import Head from "next/head";
import { useEffect, useState } from "react";
import { v4 } from "uuid";
import Card from "../components/Card";
import Filter from "../components/Filter";

export default function Home() {
  const [originalData, setOriginalData] = useState(null);
  const [cardData, setCardData] = useState(null);
  const [openFilter, setOpenFilter] = useState(false);
  const [filterArray, setFilterArray] = useState([]);

  useEffect(() => {
    fetch("http://localhost:8000/resource")
      .then((res) => {
        return res.json();
      })
      .then((data) => (setCardData(data), setOriginalData(data)));
  }, []);

  return (
    <div className="w-full h-auto bg-bodyColor pb-10">
      <Head>
        <title>static-job-listings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full h-[156px] bg-headerColor  bg-mobile-header sm:bg-desktop-header bg-no-repeat relative">
        {openFilter && (
          <Filter
            setOpenFilter={setOpenFilter}
            openFilter={openFilter}
            setFilterArray={setFilterArray}
            cardData={cardData}
            setCardData={setCardData}
            originalData={originalData}
            filterArray={filterArray}
          />
        )}
      </header>

      <main
        className={
          openFilter
            ? "mt-32 flex flex-col gap-12 sm:gap-6"
            : "mt-16 flex flex-col gap-12 sm:gap-6"
        }
      >
        {cardData &&
          cardData.map((eachData) => {
            return (
              <Card
                key={v4()}
                eachData={eachData}
                filterArray={filterArray}
                setFilterArray={setFilterArray}
                setOpenFilter={setOpenFilter}
                cardData={cardData}
                setCardData={setCardData}
                originalData={originalData}
              />
            );
          })}
      </main>
    </div>
  );
}
